### ISSUE TITLE
setup stops at "Insert consumerKey"

### ISSUE THREAD

**Issue by tomhull** [GliderGeek/pocket2rm#9]
I have followed the install process but it appears to hang after I enter my consumerKey.

I'm using Ubuntu 20.04 LTS

**Comment by technimad** [comment]
I can confirm this issue. I'm experiencing the same.

**Comment by stiliajohny** [comment]
same issue here

**Comment by stiliajohny** [comment]
however,
the first time it might hang after the key is imported
try again 
it should be open a browser window. 
then you auth and it might get stuck again.
close the browser window
try again

**Comment by tomhull** [comment]
thank you, I repeated the processes, and knowing that a browser was needed I installed one (it's a headless machine)
I can confirm this is now working for me.

**Comment by GliderGeek** [comment]
@tomhull : thanks for reporting back. i never thought about the case of a headless machine. (out of curiosity: what was the reason to do this?)

the browser is needed for the OAuth flow of pocket unfortunately.

things i can improve on my side:
- list necessity of browser
- improve messages in terminal (log when waiting browser, maybe even error out with clear message when this does not succeed)

UPDATE: currently the error of opening the browser is not handled https://github.com/GliderGeek/pocket2rm/blob/master/cmd/pocket2rm-setup/main.go#L60

**Comment by tomhull** [comment]
No problem, I'm running windows 10 with the linux subsystem.

**Comment by GliderGeek** [comment]
added the necessity of a browser in the prerequisites. if anything else is going on, this can be re-opened
